In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("C:/Users/Artophilic/Analysis Projects/Swiggy_order_analysis/Data/Rider-Info.csv")
df.head()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
0,2021-01-26 02:21:35,556753,2021-01-26 00:00:00,2021-01-26 02:21:59,2021-01-26 02:22:08,2021-01-26 02:32:51,2021-01-26 02:49:47,11696,1.5666,2.65,46.0,46.0,0,0.0,621.0,NaN,NaN,NaN,NaN,NaN
1,2021-01-26 02:33:16,556754,2021-01-26 00:00:00,2021-01-26 02:33:57,2021-01-26 02:34:45,2021-01-26 02:50:25,2021-01-26 03:11:15,18117,2.5207,2.76,8.0,8.0,0,0.0,105.0,NaN,NaN,NaN,3.266667,NaN
2,2021-01-26 02:39:49,556755,2021-01-26 00:00:00,2021-01-26 02:39:57,2021-01-26 02:40:13,2021-01-26 02:56:00,2021-01-26 03:12:46,18623,2.2074,4.80,1.0,1.0,0,0.0,66.0,NaN,NaN,NaN,9.816667,NaN
3,2021-01-26 02:47:53,556756,2021-01-26 00:00:00,2021-01-26 02:48:25,2021-01-26 02:49:06,2021-01-26 03:21:51,2021-01-26 03:41:05,15945,2.1894,6.38,1.0,1.0,0,0.0,127.0,NaN,NaN,NaN,17.533333,NaN
4,2021-01-26 03:06:30,556757,2021-01-26 00:00:00,2021-01-26 03:07:21,2021-01-26 03:07:57,2021-01-26 03:31:38,2021-01-26 04:00:15,17589,2.7870,4.01,34.0,34.0,0,0.0,84.0,NaN,NaN,NaN,1.350000,NaN

In [4]:
#Converting the time columns to datetime format

time_columns = ['order_time', 'order_date', 'allot_time', 'accept_time', 'pickup_time', 'delivered_time', 'cancelled_time']

for col in time_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [5]:
#Filling Reassignment columns
df['reassignment_method'] = df['reassignment_method'].fillna('No Reassignment')
df['reassignment_reason'] = df['reassignment_reason'].fillna('No Reassignment')

In [10]:
df['reassigned_order'] = np.where(df['reassignment_method'] != 'No Reassignment', 1, 0)

In [7]:
#rider baseline performance columns
rider_metrics = ['alloted_orders', 'delivered_orders', 'undelivered_orders', 'lifetime_order_count']
for metric in rider_metrics:
    df[metric] = df[metric].fillna(0).astype(int)

In [ ]:
#Generate a unique composite key for the Geography Dimension
df['location_id'] = df.groupby(['first_mile_distance', 'last_mile_distance']).ngroup() + 1

In [11]:
df.head()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,...,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time,reassignment_order,location_id
0,2021-01-26 02:21:35,556753,2021-01-26,2021-01-26 02:21:59,2021-01-26 02:22:08,2021-01-26 02:32:51,2021-01-26 02:49:47,11696,1.5666,2.65,...,0,0,621,No Reassignment,No Reassignment,0,NaN,NaT,0,293071
1,2021-01-26 02:33:16,556754,2021-01-26,2021-01-26 02:33:57,2021-01-26 02:34:45,2021-01-26 02:50:25,2021-01-26 03:11:15,18117,2.5207,2.76,...,0,0,105,No Reassignment,No Reassignment,0,3.266667,NaT,0,408708
2,2021-01-26 02:39:49,556755,2021-01-26,2021-01-26 02:39:57,2021-01-26 02:40:13,2021-01-26 02:56:00,2021-01-26 03:12:46,18623,2.2074,4.80,...,0,0,66,No Reassignment,No Reassignment,0,9.816667,NaT,0,377161
3,2021-01-26 02:47:53,556756,2021-01-26,2021-01-26 02:48:25,2021-01-26 02:49:06,2021-01-26 03:21:51,2021-01-26 03:41:05,15945,2.1894,6.38,...,0,0,127,No Reassignment,No Reassignment,0,17.533333,NaT,0,375072
4,2021-01-26 03:06:30,556757,2021-01-26,2021-01-26 03:07:21,2021-01-26 03:07:57,2021-01-26 03:31:38,2021-01-26 04:00:15,17589,2.7870,4.01,...,0,0,84,No Reassignment,No Reassignment,0,1.350000,NaT,0,428082

In [13]:
df['session_time'] = df['session_time'].fillna(df['session_time'].median())

In [12]:
df.isnull().sum()

order_time                   0
order_id                     0
order_date                   0
allot_time                   0
accept_time                157
pickup_time               2421
delivered_time            5218
rider_id                     0
first_mile_distance          0
last_mile_distance           0
alloted_orders               0
delivered_orders             0
cancelled                    0
undelivered_orders           0
lifetime_order_count         0
reassignment_method          0
reassignment_reason          0
reassigned_order             0
session_time              3675
cancelled_time          444782
reassignment_order           0
location_id                  0
dtype: int64

In [14]:
df.to_csv("C:/Users/Artophilic/Analysis Projects/Swiggy_order_analysis/Data/Cleaned_Order_Info.csv", index=False)